/**
CREATE MATERIALIZED VIEW View_Name

BUILD [IMMEDIATE/DEFERRED]

REFRESH [FAST/COMPLETE/FORCE]

ON [COMMIT/DEMAND]

**/

CREATE MATERIALIZED VIEW MV_Movie 
BUILD DEFERRED REFRESH COMPLETE
ON DEMAND AS SELECT * FROM movie;


SELECT * FROM MV_Movie;

-- Below is the code used to refresh the materialized view
BEGIN
DBMS_SNAPSHOT.REFRESH('MV_Movie');
END;

SELECT * 
FROM MV_Movie;

--DROP materialized view

DROP MATERIALIZED VIEW  MV_Movie;